- id: wizcli-scan-dir
  name: wizcli-scan-dir
  description: Use WizCLI to scan your code
  pass_filenames: false
  language: system
  entry: wizcli scan dir
  args: ["--use-device-code", "--no-publish", "."]

- id: wizcli-scan-dir-secrets
  name: wizcli-scan-dir-secrets
  description: Use WizCLI to scan your code for secrets
  pass_filenames: false
  language: system
  entry: wizcli scan dir
  args: ["--use-device-code", "--no-publish", "--disabled-scanners=Vulnerability,SensitiveData,Misconfiguration,SoftwareSupplyChain,AIModels,SAST,Malware", "."]
